---
version: "1.2"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:3.0.8
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
    volumes:
      - /home/sonarr/.config/NzbDrone:/config
      - /plex/TV_Shows:/plex/TV_Shows
      - /plex/complete:/plex/complete
    ports:
      - 8989:8989
    restart: unless-stopped
